"===========================================================
" Maintainer:
"       Alan Jui : alanjui.1960@gmail.com
" Version:
"       V 0.7.0    2021/02/09 20:56
"===========================================================

" set nocompatible
set encoding=utf-8
set runtimepath+=$HOME/vimfiles
" source $HOME/vimfiles/vimrc
let g:mapleader=","
" let g:python_interpreter='python3.13'
let g:python3_host_prog="C:/Program Files/Python313/python.exe"

filetype plugin indent on       " enable filetype detection
syntax on                       " enable syntax detection
set backspace=indent,eol,start  " let backspace key work at those positions
set hidden                      " allow unsaved file buffers
set noswapfile                  " disable .swp file for current file backup during editing
set hlsearch incsearch          " highlight & search when typing
set path=.,**                   " add file finding path to all recursive subfolders

" General
set number	        " Show line numbers

set linebreak	    " Break lines at word (requires Wrap lines)
set showbreak=+++	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set showmatch	    " Highlight matching brace
set visualbell	    " Use visual bell (no beeping)

set hlsearch	    " Highlight all search results
set smartcase	    " Enable smart-case search
set ignorecase	    " Always case-insensitive
set incsearch	    " Searches for strings incrementally

set autoindent	    " Auto-indent new lines
set shiftwidth=4	" Number of auto-indent spaces
set smartindent	    " Enable smart-indent
set smarttab	    " Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab

" Advanced
set ruler	                    " Show row and column ruler information

set undolevels=1000	            " Number of undo levels

" Generated by VimConfig.com

au FocusGained,BufEnter * :silent! checktime
au FocusLost,WinLeave * :silent! w

"===========================================================
" 擴充套件(Plugins)
"===========================================================
" 需安裝之擴充套件
source C:\Users\AlanJui\vimfiles\plugins.vim

" 擴充套件設定（Configuration of Plugins)
source C:\Users\AlanJui\vimfiles\config\nerdtree.rc.vim
source C:\Users\AlanJui\vimfiles\config\ranger.vim
source C:\Users\AlanJui\vimfiles\config\fzf.vim
source C:\Users\AlanJui\vimfiles\config\surround.vim
source C:\Users\AlanJui\vimfiles\config\auto-pairs.vim
source C:\Users\AlanJui\vimfiles\config\multiple-cursors.vim
source C:\Users\AlanJui\vimfiles\config\simply-fold.vim
source C:\Users\AlanJui\vimfiles\config\nerd-commenter.vim
source C:\Users\AlanJui\vimfiles\config\change-tag-name.vim
source C:\Users\AlanJui\vimfiles\config\live-server.vim
source C:\Users\AlanJui\vimfiles\config\markdown-preview.vim
source C:\Users\AlanJui\vimfiles\config\window-swap.vim
source C:\Users\AlanJui\vimfiles\config\float-term.vim
source C:\Users\AlanJui\vimfiles\config\echodoc.vim
source C:\Users\AlanJui\vimfiles\config\plantuml-previewer.vim
source C:\Users\AlanJui\vimfiles\config\find-and-replace.vim
source C:\Users\AlanJui\vimfiles\config\vim-closetag.vim

"===========================================================
" Vim 通用設定
"===========================================================
source C:\Users\AlanJui\vimfiles\global.vim

"==========================================================
" 程式碼版面與格式設定
"==========================================================
source C:\Users\AlanJui\vimfiles\format.vim

" Fix conflicts with indentLine and vim-json
let g:vim_json_syntax_conceal=0
let g:indentLine_noConcealCursor=""
let g:indentLine_noConcealCursor="nc"

"==========================================================
" COC-NVIM 配合環境
" https://github.com/neoclide/coc.nvim/wiki/Language-servers#bash
"==========================================================
let g:coc_global_extensions = ['coc-pyright']
source C:\Users\AlanJui\vimfiles\coc-nvim.vim
source C:\Users\AlanJui\vimfiles\my-coc-config.vim
source C:\Users\AlanJui\vimfiles\config\coc-explorer.vim

"==========================================================
" 快速鍵設定
"==========================================================
source C:\Users\AlanJui\vimfiles\keymap.vim

source C:\Users\AlanJui\vimfiles\config\which-key.vim

"==========================================================
" 使用者操作介面設定
"==========================================================
source C:\Users\AlanJui\vimfiles\UI.vim

" Theme Colors
if $TERM_PROGRAM == "Apple_Terminal"
    set notermguicolors

    try
        colorscheme OceanicNext
    catch
        colorscheme gruvbox
    endtry

    let g:airline_theme='oceanicnext'

else
    source C:\Users\AlanJui\vimfiles\config\color-theme-ccc.vim
endif

" Status line
" source C:\Users\AlanJui\vimfiles\config\light-line.vim
source C:\Users\AlanJui\vimfiles\config\airline-theme.vim

"==========================================================
" 其它設定
"==========================================================
source C:\Users\AlanJui\vimfiles\Misc.vim

if has("unix")
    let s:uname = system("uname -s")
    " Do Mac stuff
    if s:uname == "Darwin\n"
        source C:\Users\AlanJui\vimfiles\vimrc.osx
    endif
endif

" set exrc

" Don't convert tab to spaces
set tabstop=4
set expandtab
set list!
if has('gui_running')
    set listchars=tab:▶\ ,trail:·,extends:\#,nbsp:.
else
    set listchars=tab:>.,trail:.,extends:\#,nbsp:.
endif


set tabstop=4
set et!
set expandtab!
set noexpandtab
setlocal list
set listchars=tab:▷▷,trail:.
" Highlight tabs as errors.
" https://vi.stackexchange.com/a/9353/3168
" match Error /\t/

" To use fzf in Vim
" set rtp+=/usr/local/opt/fzf

" set guifont=DroidSansM\ Nerd\ Font:h16
set guifont=FiraCode\ NF:h16
set guifontwide=霞鶩文楷等寬\ TC:h16

" 行號設定
set number
set relativenumber


""===========================================================
"function! RunInVenv()
"  let l:venv_python = expand('%:p:h') . '/.venv/Scripts/python.exe'
"  execute '!'. l:venv_python . ' %'
"endfunction
"command! RunVenv call RunInVenv()

